---
# Tasks file for ansible-role-gnome-extensions: Install Extension

- name: Install extension with gnome-shell-extension-tool.
  ansible.builtin.command: "gnome-extensions enable {{ gnome_extension_uuid }}" # noqa no-changed-when
  become: true
  become_user: "{{ gnome_user }}"
