---
# Tasks file for ansible-role-gnome-extensions: Uninstall Extension

- name: Uninstall extension with gnome-extensions
  ansible.builtin.command: "gnome-extensions disable {{ gnome_extension_uuid }}" # noqa no-changed-when
  become: "{{ gnome_user }}"
